name: amparo_coletivo
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.31.0"

dependencies:
  flutter:
    sdk: flutter
  shimmer: ^3.0.0
  skeletonizer: ^2.0.1
  supabase_flutter: ^1.0.0
  flutter_riverpod: ^2.0.0
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
