name: amparo_coletivo
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.31.0"

dependencies:
  flutter:
    sdk: flutter
  shimmer: ^3.0.0
  provider: ^6.1.1
  supabase_flutter: ^2.9.1
  skeletonizer: ^2.0.1
  flutter_riverpod: ^2.0.0
  logger: ^2.0.2
  carousel_slider: ^5.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

