name: amparo_coletivo
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.31.0"

dependencies:
  flutter:
    sdk: flutter

  # Estado, injeção de dependência e gerenciamento de tema
  provider: ^6.1.1
  flutter_riverpod: ^2.0.0

  # Supabase
  supabase_flutter: ^2.9.1

  # Efeitos visuais
  shimmer: ^3.0.0
  skeletonizer: ^2.0.1
  carousel_slider: ^5.1.1
  photo_view: ^0.15.0
  url_launcher: ^6.3.1

  # Logs
  logger: ^2.0.2

  # Pacotes para geração e manipulação de QR Code
  qr_flutter: ^4.1.0 # Geração de QR Code visual
  image: ^4.1.3 # Manipulação de imagem para salvar como PNG
  path_provider: ^2.1.1 # Para pegar diretórios temporários, etc.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   (Você pode ativar essas fontes se estiver usando)
