name: amparo_coletivo
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.32.4"

dependencies:
  flutter:
    sdk: flutter
  shimmer: ^3.0.0
  provider: ^6.1.1
  supabase_flutter: ^2.9.1
  skeletonizer: ^2.0.1
  flutter_riverpod: ^2.0.0
  logger: ^2.0.2
  carousel_slider: ^5.1.1
  url_launcher: ^6.3.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
    - family: NunitoBold
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
    - family: NunitoLight
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Light.ttf
    - family: NunitoSemiBold
      fonts:
        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
    - family: NunitoExtraBold
      fonts:
        - asset: assets/fonts/Nunito/Nunito-ExtraBold.ttf
    - family: Arimo
      fonts:
        - asset: assets/fonts/Arimo/Arimo-Regular.ttf
    - family: ArimoBold
      fonts:
        - asset: assets/fonts/Arimo/Arimo-Bold.ttf
    - family: ArimoLight
      fonts:
        - asset: assets/fonts/Arimo/Arimo-Light.ttf
    - family: ArimoSemiBold
      fonts:
        - asset: assets/fonts/Arimo/Arimo-SemiBold.ttf
    - family: ArimoExtraBold
      fonts:
        - asset: assets/fonts/Arimo/Arimo-ExtraBold.ttf
    - family: ArimoBlack
      fonts:
        - asset: assets/fonts/Arimo/Arimo-Black.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
    - family: RobotoBold
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
    - family: RobotoLight
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
    - family: RobotoMedium
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
    - family: RobotoThin
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
